setup.py
src/eduid_idp/__init__.py
src/eduid_idp/cache.py
src/eduid_idp/config.py
src/eduid_idp/idp.py
src/eduid_idp/idp_actions.py
src/eduid_idp/idp_user.py
src/eduid_idp/login.py
src/eduid_idp/logout.py
src/eduid_idp/sso_session.py
src/eduid_idp/testing.py
src/eduid_idp/tests/test_expiringCache.py

First batch of changes. More refactoring planned.

Redis sessions

---

.travis.yml
setup.py
src/eduid_idp/cache.py
src/eduid_idp/idp.py
src/eduid_idp/idp_actions.py
src/eduid_idp/idp_user.py
src/eduid_idp/mischttp.py
src/eduid_idp/tests/test_SSO.py
src/eduid_idp/tests/test_actions.py
src/eduid_idp/util.py

Don't merge this PR until Travis reports success with 3.x

Python3 fixes

---

src/eduid_idp/config.py
src/eduid_idp/idp_actions.py

Allow action plugins to be loaded through a config setting rather than setuptools entry points.

Eperez new actions

---

docker/setup.sh

install correct dependencies in the docker image

install correct dependencies in the docker image

---

requirements.txt
setup.py
src/eduid_idp/config.py
src/eduid_idp/idp_actions.py
src/eduid_idp/tests/data/test_actions.ini
src/eduid_idp/tests/test_actions.py
src/eduid_idp/tests/test_idPUserDb.py
src/eduid_idp/util.py

Adapt to new userdb actions api
use secret box and eppn for login tokens

Eperez eppn comm

---

requirements.txt
setup.py
src/eduid_idp/idp_actions.py

This depends on the last eduid-action and also checks in the db for actions created with both userid or eppn to identify the users.

Eperez actions api

---

requirements.txt
setup.py
src/eduid_idp/config.py
src/eduid_idp/idp.py
src/eduid_idp/login.py
src/eduid_idp/mischttp.py
src/eduid_idp/service.py

* Sanitize user inputs, this fixes a XSS vulnerability in the redirect_url param for the /verify view (found by John using Burp)
* Also fixes an open redirect in the /verify view

sanitize user inputs

---

src/eduid_idp/tests/test_actions.py

Test the tou_action and mfa_action modules

Eperez test actions

---

.travis.yml
requirements.txt
setup.py
src/eduid_idp/config.py
src/eduid_idp/idp.py
src/eduid_idp/idp_actions.py
src/eduid_idp/login.py
src/eduid_idp/mfa_action.py
src/eduid_idp/service.py
src/eduid_idp/testing.py
src/eduid_idp/tests/data/test_actions.ini
src/eduid_idp/tests/test_SSO.py
src/eduid_idp/tests/test_actions.py
src/eduid_idp/tests/test_idPUserDb.py
src/eduid_idp/util.py

Move authn data for actions from the URL to the session

Eperez session token

---

requirements.txt
src/eduid_idp/tests/test_actions.py

Redis temporary instance moved to its own module

Eperez redis testing

---

requirements.txt
src/eduid_idp/idp.py
src/eduid_idp/idp_actions.py
src/eduid_idp/login.py
src/eduid_idp/shared_session.py
src/eduid_idp/tests/test_actions.py
src/eduid_idp/tests/test_shared_session.py

Eperez re shared session

---

src/eduid_idp/idp.py
src/eduid_idp/login.py
src/eduid_idp/shared_session.py

remove transitional upper case adapter

remove upper case adapter

---

src/eduid_idp/idp.py
src/eduid_idp/login.py
src/eduid_idp/shared_session.py

Revert "remove upper case adapter"

---

requirements.txt
setup.py
src/eduid_idp/login.py

Depends on https://github.com/SUNET/eduid-common/pull/217

Lundberg pick algorithms

---

src/eduid_idp/idp.py
src/eduid_idp/login.py
src/eduid_idp/shared_session.py

Revert "Revert "remove upper case adapter""

---

src/eduid_idp/idp.py
src/eduid_idp/login.py
src/eduid_idp/logout.py

Return a 403 for SSO request when there is a session and the corresponding user is terminated

Eperez no terminated

---

src/eduid_idp/login.py

This way the user will get to the login view if she tries again.

Remove sso session if the user is terminated

---

requirements.txt
setup.py
src/eduid_idp/testing.py

Remove deprecated call to IdPUser.__init__

Eperez user init 2

---

requirements.txt
setup.py
src/eduid_idp/tests/test_SSO.py
src/eduid_idp/tests/test_actions.py

Remove deprecated direct calls to `Element.__init__`

Eperez elem init 1

---

requirements.txt
setup.py
src/eduid_idp/idp_actions.py
src/eduid_idp/mfa_action.py

Use credential.key rather than credential as key in dict.

Eperez elem init 4

---

requirements.txt
setup.py
src/eduid_idp/testing.py
src/eduid_idp/tests/test_actions.py
src/eduid_idp/tests/test_idPUserDb.py

Turn User into dataclass
* User.passwords -> User.credentials
* Fix tests wrt created_ts new default value

Eperez user init 1

---

requirements.txt
setup.py
src/eduid_idp/login.py
src/eduid_idp/tests/test_actions.py

Depends on https://github.com/SUNET/eduid-userdb/pull/181 and https://github.com/SUNET/eduid-common/pull/267
Closes #115

Lundberg new attributes
